// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Models;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(GardeshgariDbContext))]
    [Migration("20230706233302_create_d")]
    partial class create_d
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyProject.Models.Pagegroup", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("GroupTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("Pagegroups");

                    b.HasData(
                        new
                        {
                            GroupID = 10,
                            GroupTitle = "خرم اباد "
                        },
                        new
                        {
                            GroupID = 11,
                            GroupTitle = "الشتر  "
                        },
                        new
                        {
                            GroupID = 12,
                            GroupTitle = " دورود  "
                        });
                });

            modelBuilder.Entity("MyProject.Models.Pagesloc", b =>
                {
                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID");

                    b.HasIndex("GroupID");

                    b.ToTable("Pageslocs");
                });

            modelBuilder.Entity("MyProject.Models.Pagesloc", b =>
                {
                    b.HasOne("MyProject.Models.Pagegroup", "Pagegroup")
                        .WithMany("Pageslocs")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagegroup");
                });

            modelBuilder.Entity("MyProject.Models.Pagegroup", b =>
                {
                    b.Navigation("Pageslocs");
                });
#pragma warning restore 612, 618
        }
    }
}
